apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-lb-service 
spec:
  type: LoadBalancer 
  selector:
    app: myapp 
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
        #nodePort: 31231 # NodePort
